name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag acoustic_feature_extractor:latest

    - name: Test
      run: |-
        docker run \
          acoustic_feature_extractor:latest \
          python -m unittest -v

    - name: Test pip install
      run: |-
        docker run \
          acoustic_feature_extractor:latest \
          bash -c 'pip install git+https://github.com/Hiroshiba/acoustic_feature_extractor'
