name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag acoustic_feature_extractor:latest

    - name: Test
      run: |-
        docker run \
          -v `pwd`:`pwd` \
          -w `pwd` \
          acoustic_feature_extractor:latest \
          pytest -s -v ./tests/

    - name: Test pip install
      run: |-
        docker run \
          -v `pwd`:`pwd` \
          -w `pwd` \
          acoustic_feature_extractor:latest \
          bash -c 'pip install git+https://github.com/Hiroshiba/acoustic_feature_extractor'
